# -*- coding: utf-8 -*-
"""
/***************************************************************************

/***************************************************************************
 spotSpraying
                                 A QGIS plugin
 spotSpraying
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-08-03
        copyright            : (C) 2022 by OpenGeoLabs'
        email                : terezpohankova@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

"""

__author__ = 'Tereza Pohankova'
__date__ = '2022-08-03'
__copyright__ = '(C) 2022 by OpenGeoLabs' 
# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load spotSpraying class from file spotSpraying.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .spotSpraying import spotSprayingPlugin
    return spotSprayingPlugin()
